(() => {
  const TAG = 'nmx-project-showcase';
  if (customElements.get(TAG)) return;

  const CDN = 'https://cdn.jsdelivr.net/gh/danteobregon90-ui/nmx-wix-widget@main/assets';

  class NmxProjectShowcase extends HTMLElement {
    connectedCallback() {
      if (this.shadowRoot) return;
      const root = this.attachShadow({ mode: 'open' });
      root.innerHTML = `
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&family=Syne:wght@500;600;700;800&display=swap');
          :host{display:block;width:100%;background:#123c40;color:#123c40;font-family:'Manrope','Pluto Sans',Arial,sans-serif}
          *{box-sizing:border-box} a{color:inherit} .shell{width:100%;overflow:hidden;background:#e8fff4}
          .top{height:42px;padding:0 clamp(24px,5vw,84px);display:flex;align-items:center;justify-content:space-between;background:#0a292c;color:#b8d4ce;font-size:11px;letter-spacing:.12em;text-transform:uppercase}
          .top strong{color:#3ee29e}.nav{height:92px;padding:0 clamp(24px,5vw,84px);display:flex;align-items:center;justify-content:space-between;background:rgba(18,60,64,.98);color:white;border-bottom:1px solid rgba(255,255,255,.11)}
          .logo{width:160px;height:auto;display:block}.navlinks{display:flex;gap:30px;align-items:center;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.navlinks a{text-decoration:none;color:#d8ede9}.navlinks .contact{padding:13px 18px;border:1px solid #3ee29e;color:#3ee29e}
          .hero{position:relative;min-height:760px;display:grid;grid-template-columns:minmax(0,1.03fr) minmax(420px,.97fr);background:#123c40;color:#fff}
          .heroCopy{position:relative;z-index:2;padding:100px 5vw 90px clamp(24px,5vw,84px);display:flex;flex-direction:column;justify-content:center;background:linear-gradient(135deg,#0b3033 0%,#123c40 68%,#165156 100%)}
          .heroCopy:after{content:'';position:absolute;inset:0;opacity:.12;background-image:linear-gradient(rgba(255,255,255,.13) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.13) 1px,transparent 1px);background-size:54px 54px;pointer-events:none}
          .heroCopy>*{position:relative;z-index:1}.kicker{display:flex;align-items:center;gap:14px;color:#3ee29e;font-size:12px;font-weight:800;letter-spacing:.22em;text-transform:uppercase}.kicker:before{content:'';width:48px;height:2px;background:#3ee29e}
          h1,h2,h3{font-family:'Syne','Polyphonic',Arial,sans-serif}.hero h1{font-size:clamp(54px,6vw,92px);line-height:.94;letter-spacing:-.055em;margin:28px 0 30px;max-width:850px}.hero h1 span{color:#3ee29e}.hero p{max-width:680px;margin:0;color:#d5e9e5;font-size:clamp(17px,1.45vw,22px);line-height:1.65}
          .heroActions{display:flex;gap:14px;flex-wrap:wrap;margin-top:38px}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:52px;padding:0 23px;text-decoration:none;font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.primary{background:#3ee29e;color:#092a2d}.ghost{border:1px solid rgba(255,255,255,.45);color:#fff}
          .heroVisual{position:relative;min-height:760px;background:url('${CDN}/garza.jpg') center/cover no-repeat}.heroVisual:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(18,60,64,.55),transparent 38%),linear-gradient(0deg,rgba(8,35,38,.72),transparent 50%)}
          .projectTag{position:absolute;left:34px;right:34px;bottom:34px;padding:25px 28px;background:rgba(8,35,38,.88);backdrop-filter:blur(12px);border-left:4px solid #3ee29e}.projectTag small{color:#3ee29e;letter-spacing:.17em;text-transform:uppercase;font-weight:800}.projectTag h3{font-size:25px;margin:8px 0 4px}.projectTag span{font-size:13px;color:#cde1dd}
          .stats{display:grid;grid-template-columns:repeat(4,1fr);padding:0 clamp(24px,5vw,84px);background:#fff;border-bottom:1px solid #d8e8e4}.stat{padding:38px 26px;border-right:1px solid #d8e8e4}.stat:last-child{border:0}.stat b{display:block;font-family:'Syne';font-size:36px;color:#123c40}.stat span{display:block;margin-top:7px;color:#69807c;font-size:11px;letter-spacing:.12em;text-transform:uppercase}
          .intro{padding:115px clamp(24px,5vw,84px);display:grid;grid-template-columns:.85fr 1.15fr;gap:8vw;background:#e8fff4}.sectionLabel{color:#179a69;font-weight:800;font-size:11px;letter-spacing:.2em;text-transform:uppercase}.intro h2,.projects h2,.value h2{font-size:clamp(40px,5vw,68px);line-height:1.02;letter-spacing:-.045em;margin:18px 0 0}.introText{padding-top:30px}.introText p{font-size:19px;line-height:1.75;color:#4c6561;margin:0 0 34px}.pillgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.pill{background:#fff;padding:20px;border-left:3px solid #3ee29e;font-size:13px;font-weight:700;color:#123c40}
          .services{background:#0b3033;color:white;padding:105px clamp(24px,5vw,84px)}.servicesHead{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:52px}.services h2{font-size:clamp(40px,5vw,68px);line-height:1;letter-spacing:-.04em;margin:16px 0 0}.servicesHead p{max-width:480px;color:#b9d1cc;line-height:1.7}.serviceGrid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid rgba(255,255,255,.14);border-left:1px solid rgba(255,255,255,.14)}
          .service{min-height:250px;padding:32px;border-right:1px solid rgba(255,255,255,.14);border-bottom:1px solid rgba(255,255,255,.14);transition:.25s}.service:hover{background:#123c40}.service .n{color:#3ee29e;font-size:11px;letter-spacing:.15em}.service h3{font-size:23px;margin:55px 0 12px}.service p{color:#a9c4bf;font-size:14px;line-height:1.6;margin:0}
          .projects{padding:115px clamp(24px,5vw,84px);background:#f7faf9}.projectsHead{display:flex;align-items:end;justify-content:space-between;margin-bottom:50px}.projectGrid{display:grid;grid-template-columns:1.25fr .75fr;grid-template-rows:330px 330px;gap:18px}.pCard{position:relative;overflow:hidden;color:white;background:#123c40}.pCard:first-child{grid-row:1/3}.pCard img{width:100%;height:100%;object-fit:cover;transition:.55s}.pCard:hover img{transform:scale(1.035)}.pCard:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,rgba(5,27,29,.92),transparent 60%)}.pInfo{position:absolute;z-index:2;left:30px;right:30px;bottom:28px}.pInfo small{color:#3ee29e;font-weight:800;letter-spacing:.16em}.pInfo h3{font-size:clamp(21px,2.1vw,32px);margin:8px 0 5px}.pInfo span{font-size:13px;color:#d2e4e0}
          .value{padding:110px clamp(24px,5vw,84px);display:grid;grid-template-columns:1fr 1fr;gap:7vw;background:#123c40;color:#fff}.value h2{margin-bottom:28px}.value p{color:#bad1cc;font-size:17px;line-height:1.7}.valueList{display:grid;gap:10px}.valueItem{display:flex;align-items:center;gap:16px;padding:21px 22px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.1);font-weight:700}.valueItem b{color:#3ee29e;font-family:'Syne'}
          .ctaBand{display:grid;grid-template-columns:1.35fr .65fr;align-items:center;padding:75px clamp(24px,5vw,84px);background:#3ee29e;color:#092a2d}.ctaBand h2{font-size:clamp(36px,4.5vw,62px);line-height:1;margin:0}.ctaBand p{font-size:16px;line-height:1.6}.ctaBand .btn{background:#123c40;color:white;margin-top:15px}
          footer{padding:45px clamp(24px,5vw,84px);background:#08272a;color:#9bb8b3;display:flex;justify-content:space-between;gap:30px;font-size:12px;line-height:1.8}footer strong{color:white}footer a{color:#3ee29e;text-decoration:none}
          @media(max-width:950px){.navlinks{display:none}.hero{grid-template-columns:1fr}.heroVisual{min-height:580px}.stats{grid-template-columns:repeat(2,1fr)}.intro,.value{grid-template-columns:1fr}.serviceGrid{grid-template-columns:repeat(2,1fr)}.projectGrid{grid-template-columns:1fr;grid-template-rows:460px 320px 320px}.pCard:first-child{grid-row:auto}.ctaBand{grid-template-columns:1fr}.ctaBand>div:last-child{margin-top:20px}}
          @media(max-width:620px){.top{display:none}.nav{height:76px}.logo{width:125px}.heroCopy{padding:78px 24px}.heroVisual{min-height:480px}.stats{grid-template-columns:1fr 1fr}.stat{padding:25px 16px}.stat b{font-size:28px}.intro,.services,.projects,.value{padding:80px 24px}.serviceGrid{grid-template-columns:1fr}.servicesHead,.projectsHead{display:block}.projectGrid{grid-template-rows:420px 300px 300px}.pillgrid{grid-template-columns:1fr}.ctaBand{padding:60px 24px}footer{display:block;padding:40px 24px}}
        </style>
        <div class="shell">
          <div class="top"><span>NMX Servicios y Comercio Industrial S.A. de C.V.</span><span><strong>Ingeniería · Construcción · Infraestructura</strong></span></div>
          <nav class="nav"><img class="logo" src="${CDN}/logo-white.png" alt="NMX"><div class="navlinks"><a href="#capacidades">Capacidades</a><a href="#proyectos">Proyectos</a><a href="#valor">Valor estratégico</a><a class="contact" href="#contacto">Contacto</a></div></nav>
          <section class="hero"><div class="heroCopy"><span class="kicker">Infraestructura que trasciende</span><h1>Capacidad técnica para construir <span>lo que sigue.</span></h1><p>Desarrollamos y ejecutamos proyectos de construcción, infraestructura carretera, edificación vertical y sistemas industriales especializados bajo un solo responsable técnico.</p><div class="heroActions"><a class="btn primary" href="#proyectos">Ver proyectos</a><a class="btn ghost" href="#contacto">Presentar un proyecto</a></div></div><div class="heroVisual"><div class="projectTag"><small>Proyecto destacado · Grupo INDI</small><h3>Hutchison Ports LCT · Etapa III</h3><span>Red hidráulica de alta presión y estación de suministro tipo garza</span></div></div></section>
          <section class="stats"><div class="stat"><b>600 m</b><span>Red hidráulica instalada</span></div><div class="stat"><b>360°</b><span>Gestión integral</span></div><div class="stat"><b>24/7</b><span>Continuidad operativa</span></div><div class="stat"><b>1</b><span>Responsable técnico</span></div></section>
          <section class="intro" id="capacidades"><div><span class="sectionLabel">Perfil corporativo</span><h2>Construcción con ingeniería. Ejecución con control.</h2></div><div class="introText"><p>NMX integra disciplinas civiles, electromecánicas, hidráulicas, sanitarias y energéticas para desarrollar proyectos de alta complejidad en entornos industriales, portuarios, carreteros, hospitalarios y corporativos.</p><div class="pillgrid"><div class="pill">Planeación técnica y operativa</div><div class="pill">Control de calidad, costo y tiempo</div><div class="pill">Coordinación multidisciplinaria</div><div class="pill">Entrega documentada y validada</div></div></div></section>
          <section class="services"><div class="servicesHead"><div><span class="sectionLabel">Áreas de especialización</span><h2>Capacidad multidisciplinaria.</h2></div><p>Soluciones integrales y escalables para proyectos donde la confiabilidad, la precisión técnica y la continuidad operativa no son opcionales.</p></div><div class="serviceGrid"><article class="service"><span class="n">01</span><h3>Carreteras y puentes</h3><p>Terracerías, drenaje, bases, pavimentación, estructuras y obras complementarias.</p></article><article class="service"><span class="n">02</span><h3>Edificación vertical</h3><p>Construcción, rehabilitación, estructuras, acabados e integración de instalaciones.</p></article><article class="service"><span class="n">03</span><h3>Obra industrial</h3><p>Montaje especializado, sistemas electromecánicos y soluciones para operación continua.</p></article><article class="service"><span class="n">04</span><h3>Agua y saneamiento</h3><p>Redes hidráulicas, drenaje sanitario y pluvial, PTAR y obra complementaria.</p></article><article class="service"><span class="n">05</span><h3>Energía y respaldo</h3><p>Motogeneradores, UPS, tableros, transferencia automática y distribución eléctrica.</p></article><article class="service"><span class="n">06</span><h3>HVAC especializado</h3><p>Diseño, instalación y mantenimiento para hospitales, industria y áreas críticas.</p></article></div></section>
          <section class="projects" id="proyectos"><div class="projectsHead"><div><span class="sectionLabel">Experiencia comprobada</span><h2>Proyectos ejecutados.</h2></div></div><div class="projectGrid"><article class="pCard"><img src="${CDN}/garza.jpg" alt="Estación de suministro tipo garza en Hutchison Ports LCT"><div class="pInfo"><small>PUERTO DE LÁZARO CÁRDENAS</small><h3>Hutchison Ports LCT · Tercera Etapa</h3><span>Infraestructura hidráulica · Cliente: Grupo INDI</span></div></article><article class="pCard"><img src="${CDN}/santa-casilda.jpg" alt="Obra de drenaje transversal en Autopista Santa Casilda"><div class="pInfo"><small>INFRAESTRUCTURA CARRETERA</small><h3>Autopista Santa Casilda</h3><span>Drenaje transversal y estructuras complementarias</span></div></article><article class="pCard"><img src="${CDN}/excavacion-portuaria.jpg" alt="Excavación portuaria en Hutchison Ports LCT"><div class="pInfo"><small>EJECUCIÓN EN CAMPO</small><h3>Obra hidráulica portuaria</h3><span>Excavación, tubería, cimentación y pruebas</span></div></article></div></section>
          <section class="value" id="valor"><div><span class="sectionLabel">Valor estratégico</span><h2>Más control. Menos riesgo.</h2><p>Operamos como socio estratégico para asegurar calidad, cumplimiento, coordinación y continuidad desde la planeación hasta la puesta en operación.</p></div><div class="valueList"><div class="valueItem"><b>01</b> Un solo responsable técnico</div><div class="valueItem"><b>02</b> Eliminación de riesgos operativos</div><div class="valueItem"><b>03</b> Reducción de costos ocultos</div><div class="valueItem"><b>04</b> Cumplimiento normativo</div><div class="valueItem"><b>05</b> Soluciones integrales y escalables</div></div></section>
          <section class="ctaBand" id="contacto"><h2>Convirtamos el reto técnico en una obra ejecutada.</h2><div><p>Cuéntenos el alcance de su proyecto. Nuestro equipo integrará la solución técnica, operativa y administrativa.</p><a class="btn" href="https://wa.me/524421811481" target="_blank" rel="noopener">Contactar a NMX</a></div></section>
          <footer><div><strong>NMX Servicios y Comercio Industrial S.A. de C.V.</strong><br>Calle Tzararacua No. 11, Col. Las 600 Casas<br>Lázaro Cárdenas, Michoacán, C.P. 60954</div><div><strong>Contacto corporativo</strong><br>(753) 688 3530 · WhatsApp (442) 181 1481<br><a href="mailto:direccion@nmxindustrial.com">direccion@nmxindustrial.com</a></div></footer>
        </div>`;
    }
  }
  customElements.define(TAG, NmxProjectShowcase);
})();
